Replace remaining Mozilla VPN branding

diff --git a/macos/pkg/scripts/postinstall.in b/macos/pkg/scripts/postinstall.in
--- a/macos/pkg/scripts/postinstall.in
+++ b/macos/pkg/scripts/postinstall.in
@@ -6,7 +6,7 @@
 
 set -eu
 
-APP_DIR="$2/Mozilla VPN.app"
+APP_DIR="$2/WG Desktop.app"
 LOG_DIR=/var/log/mozillavpn
 
 OSX_MAJOR_VER=$(sw_vers -productVersion | cut -d. -f1)
@@ -19,9 +19,9 @@ chmod 755 $LOG_DIR
 exec 2>&1 > $LOG_DIR/postinstall.log
 
 echo "Running postinstall at $(date)"
-echo "Installing Mozilla VPN to ${APP_DIR}"
+echo "Installing WG Desktop to ${APP_DIR}"
 
-pkill -U "${USER}" -x "Mozilla VPN" || echo "Unable to kill GUI, not running?"
+pkill -U "${USER}" -x "WG Desktop" || echo "Unable to kill GUI, not running?"
 sleep 1
 
 if [ ${OSX_MAJOR_VER} -lt 13 ]; then
